"""Add lat, lng of location

Revision ID: 55b6e85b380
Revises: 41a42a4e735
Create Date: 2015-05-23 12:27:01.116768

"""

# revision identifiers, used by Alembic.
revision = '55b6e85b380'
down_revision = '41a42a4e735'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('location_lat', sa.Float(), server_default=sa.text('0.0'), nullable=True))
    op.add_column('meetings', sa.Column('location_lng', sa.Float(), server_default=sa.text('0.0'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'location_lng')
    op.drop_column('meetings', 'location_lat')
    ### end Alembic commands ###
