"""Add a table for presented slides

Revision ID: 89f95a5952fe
Revises: 55b6e85b380
Create Date: 2016-02-09 01:11:38.035307

"""

# revision identifiers, used by Alembic.
revision = '89f95a5952fe'
down_revision = '55b6e85b380'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('presenter_id', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('memo', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('registered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['presenter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    ### end Alembic commands ###
